version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: latest
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - apt-get install packer
  build:
    commands:
        - echo Build started 
        - ng build
        - ARTIFACT=`packer build -machine-readable packer-ui.json |awk -F, '$0 ~/artifact,0,id/ {print $6}'`
        - AMI_ID=`echo $ARTIFACT | cut -d ':' -f2`
        - echo 'variable "AMI_ID" { default = "'${AMI_ID}'" }' > amivar.tf
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes