version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: latest
    commands:
        - echo Installing source NPM dependencies...
        - npm install --force
        - npm install -g @angular/cli --force
        - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        - sudo apt-get update && sudo apt-get install packer
  build:
    commands:
        - echo Build started 
        - ng build --force
        - packer build -machine-readable ./packer-ui.json
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes